version: "3"
services:
  main:
    image: tariff-tool-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ${CMD:-"start"}
    network_mode: host
    volumes:
      - ./dist/:/var/www/app/dist/
      - ./src/:/var/www/app/src/
      - ./config.js:/var/www/app/config.js